language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'

before_script:
  - composer self-update
  - composer install

notifications:
  irc:
    channels:
      - "irc.hackthissite.org#cryptopaste"
    use_notice: true
    skip_join: true
