language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  - echo "extension = json.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install

notifications:
  irc: "irc.hackthissite.org#cryptopaste"
