language: php
matrix:
  include:
    - php: 7.0
      env: SYMFONY_PHPUNIT_VERSION=6.5
    - php: 7.1
      env: SYMFONY_PHPUNIT_VERSION=7.5
    - php: 7.2
    - php: 7.3
    - php: 7.4

before_script:
  - composer self-update
  - composer install

notifications:
  irc:
    channels:
      - "irc.hackthissite.org#cryptopaste"
    use_notice: true
    skip_join: true
