imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    body_max_length: 3145728
    session_lifetime: 86400
    # Casts parameter to string to avoid config concatenation errors
    table_prefix: '%database_table_prefix%'

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form:
        enabled: true
        csrf_protection:
            enabled: true
#            field_name: nonce
    csrf_protection:
        enabled: true
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        # handler_id: session.handler.native_file
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        name: cryptopaste
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        show_total: '%show_paste_total%'
        max_length: '%body_max_length%'
        pages: '@AppBundle\Twig\TwigHelper'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

doctrine_migrations:
    table_name: '%table_prefix%migration_versions'
    name: 'CryptoPaste Database Migrations'

# Swiftmailer Configuration
swiftmailer:
    transport: ~
    host: ~
    username: ~
    password: ~
    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false
